"""Expose the refund worker as an A2A server — official ADK `to_a2a`.

The worker's own code (refund_agent/agent.py) is untouched. This file only
wraps its existing `root_agent` for A2A, exactly as the ADK docs show:
https://adk.dev/a2a/quickstart-exposing/

Run:
    uvicorn a2a_server:a2a_app --host localhost --port 8043

Agent Card (auto-generated by to_a2a):
    http://localhost:8043/.well-known/agent-card.json
"""

from pathlib import Path

from dotenv import load_dotenv

# Load the worker's env (Vertex + Firestore) BEFORE importing the agent —
# tools.py creates a Firestore client at import time, so the project must be set.
load_dotenv(Path(__file__).parent / "refund_agent" / ".env")

from google.adk.a2a.utils.agent_to_a2a import to_a2a  # noqa: E402
from refund_agent.agent import root_agent  # noqa: E402

# to_a2a auto-generates the agent card, wires the A2A executor + task store,
# and mounts all A2A routes on a Starlette app. Nothing hand-made.
a2a_app = to_a2a(root_agent, port=8043)
